# ceph installation configuration
machine:
  # add machine details of mon,osd and admin.
  # format: ip_address-shorthostname
  # example - 1.1.1.1:magna001

  mon: 10.8.128.7-magna007
    10.8.128.28-magna028
    10.8.128.35-magna035
  osd: 10.8.128.37-magna037
    10.8.128.50-magna050
    10.8.128.63-magna063
  admin: 10.8.128.7-magna007

ceph_config:
  cdn_live_username: qa@redhat.com
  cdn_live_password: a85xH8a5w8EaZbdS

  rhel_pool_id: 8a85f9823e3d5e43013e3ddd4e2a0977

  cdn_enabled: false # true or false
  iso_enabled: true # true or false
  iso: http://puddle.ceph.redhat.com/distill/1.3-compose-trees/Ceph-1.3-RHEL-7-20160126.t.0/compose/Installer/x86_64/iso/Ceph-1.3-RHEL-7-20160126.t.0-x86_64-dvd.iso
  gpg_signing_on: true # true of false

repos:
  mon: rhel-7-server-rhceph-1.3-mon-rpms
  osd: rhel-7-server-rhceph-1.3-osd-rpms

  admin:
    installer: rhel-7-server-rhceph-1.3-installer-rpms
    calamari: rhel-7-server-rhceph-1.3-calamari-rpms
    tools: rhel-7-server-rhceph-1.3-tools-rpms
